name: Build Resume

on:
  push:
    branches: [ main ]  # or 'master' depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Render Resume
      run: python main.py

    - name: Upload resume HTML as artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: output/index.html
